
ArenaPetCastsDB = {
["petClasses"] = {
["DEATHKNIGHT"] = false,
["HUNTER"] = false,
["WARLOCK"] = true,
["SHAMAN"] = false,
["MAGE"] = false,
["DRUID"] = false,
["MONK"] = false,
["PRIEST"] = false,
},
["log"] = {
"09:33:36  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:33:36  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:33:36  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:33:36  === PLAYER_ENTERING_WORLD  instanceType=none ===",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:57  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:58  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:34:58  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:58  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:58  === PREP  specs=1 ===",
"09:34:58  arena1 resolved as PALADIN (spec)",
"09:34:59  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:34:59  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:34:59  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:34:59  === PLAYER_ENTERING_WORLD  instanceType=arena ===",
"09:34:59  arena1 resolved as PALADIN (spec)",
"09:35:01  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:35:01  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:35:01  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:35:01  === PREP  specs=2 ===",
"09:35:01  arena1 resolved as PALADIN (spec)",
"09:35:01  arena2 resolved as HUNTER (spec)",
"09:35:02  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:35:02  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:35:02  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:35:02  === PREP  specs=3 ===",
"09:35:02  arena1 resolved as PALADIN (spec)",
"09:35:02  arena2 resolved as HUNTER (spec)",
"09:35:02  arena3 resolved as ROGUE (spec)",
"09:35:55  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:35:55  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:35:55  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:06  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:06  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:06  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:06  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:06  arenapet2: pet exists=true  owner exists=false  class=HUNTER",
"09:36:06  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:06  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:06  arenapet2: pet exists=true  owner exists=false  class=HUNTER",
"09:36:06  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:06  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:06  arenapet2: pet exists=true  owner exists=true  class=HUNTER",
"09:36:06  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:17  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:17  arenapet2: pet exists=true  owner exists=true  class=HUNTER",
"09:36:17  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:18  arenapet1: pet exists=false  owner exists=true  class=PALADIN",
"09:36:18  arenapet2: pet exists=true  owner exists=true  class=HUNTER",
"09:36:18  arenapet3: pet exists=false  owner exists=true  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:36:58  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:36:58  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:36:58  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:37:01  arenapet1: pet exists=false  owner exists=false  class=PALADIN",
"09:37:01  arenapet2: pet exists=false  owner exists=false  class=HUNTER",
"09:37:01  arenapet3: pet exists=false  owner exists=false  class=ROGUE",
"09:37:01  === PLAYER_ENTERING_WORLD  instanceType=none ===",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet1: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet2: pet exists=false  owner exists=false  class=nil",
"09:37:15  arenapet3: pet exists=false  owner exists=false  class=nil",
},
["point"] = {
"TOP",
"TOP",
-13.4686222076416,
-145.9122009277344,
},
["bgAlpha"] = 1,
["color"] = {
0.1098039299249649,
1,
0,
},
["barHeight"] = 26,
["showSpark"] = true,
["showIcon"] = true,
["warlockOnly"] = true,
["showCaster"] = true,
["barGap"] = 4,
["showChannels"] = true,
["gap"] = 4,
["width"] = 220,
["onlyAtMe"] = true,
["ccColor"] = {
0.01568627543747425,
0.9019608497619629,
0,
},
["assumedCast"] = 1.5,
["height"] = 22,
["barColor"] = {
0,
1,
0.1882353127002716,
},
["locked"] = true,
["barWidth"] = 200,
}
